install.packages('BiocManager')
install.packages('rmarkdown')
install.packages('tidyverse')
install.packages('readxl')
install.packages('stringi')
install.packages('stringr')
install.packages("plotly")
install.packages('Gmisc')
install.packages('glue')
install.packages('grid')
install.packages('knitr')
install.packages("kableExtra")
install.packages("rmdformats")
install.packages('reshape2')

BiocManager::install('org.Hs.eg.db')
BiocManager::install('topGO')
BiocManager::install('IRanges')

BiocManager::install('pheatmap')
BiocManager::install('RColorBrewer')
BiocManager::install('cowplot')